### ISSUE TITLE
contents not updating

### ISSUE THREAD

**Issue by lexisman** [cmik/plugin.video.tfctv#11]
Hi cmik,

I noticed that the contents are not updating. for example under TV shows, some of the shows are not showing, I tried looking at by category same thing it's not there. For example,  the teleserye Viral, Broken marriage are not there, can you please tell us what to do to update the contents. I tried looking for the Tools that used to be there to update the database but I could not find it there anymore. I tried deleting the cache from the kodi itself but still the issue persist. I am using Kodi Matrix 19.3. Thank you.

Update:
I found those missing teleserye, its under the Top Series. :)

**Comment by cmik** [comment]
Hi @lexisman,
You can enable Tools in the advanced settings then it will show at the bottom of the main menu.
In the Tools menu, you can select "Check for catalog updates" (this process takes 30 minutes or more).
Hope this help.

**Comment by lexisman** [comment]
I will do that. Thanks a lot.
