### ISSUE TITLE
Error after succesfully logging in

### ISSUE THREAD

**Issue by lexisman** [cmik/plugin.video.tfctv#18]
Hi cmik,

I think tfc did another changes on their server. Just today I got this error, either using android box or windows:
Kodi version - NEXUS
tfc addon latest version
Windows 11

Error after succesfully logging in. Please see the log:
windows 11 log  -  https://paste.kodi.tv/vamedusega
android log - https://paste.kodi.tv/oyuxusamey

Thank you.

**Comment by cmik** [comment]
Hi @lexisman,
I’ve just pushed a fix in a new version 2.0.3.
You can download it from my repo.

**Comment by lexisman** [comment]
Thank you. Its working now.
