### ISSUE TITLE
Error timeout

### ISSUE THREAD

**Issue by sdstreams** [cmik/plugin.video.tfctv#4]
Hello, for the past few days I have been showing an error timeout when trying to access the addon. My sub is active and I'm on version 1.4.11. Cmik repo not allowing installation of tfc.tv addon as well. Is this something happening for everyone?

[Error Log](https://pastebin.com/raw/xz4bpqEf)

**Comment by cmik** [comment]
Hi @HenioH ,
Are you still experiencing those timeouts?
Are you logged in when using the add-on?

**Comment by cmik** [comment]
I'm closing this issue as it is too old
