### ISSUE TITLE
tfc tv Ver 1.5 error "check log for more information

### ISSUE THREAD

**Issue by C-Flick** [cmik/plugin.video.tfctv#6]
Hello there,

Since Yesterday 09/16/2020, I'm getting tfc error "check log for information". I've uninstall and reinstall tfc tv with the same error, Pls. Help... Please see the attached tfc tv log error in jpg format.
![IMG_1531](https://user-images.githubusercontent.com/66084620/93531542-40238600-f8f4-11ea-923c-014a6dd82d87.jpg)

Regards,
C-Flick

**Comment by cmik** [comment]
Hi @C-Flick ,
It seems you are still using the old login process (SSO). In the add-on settings > General > uncheck "Login with SSO" option then retry.

**Comment by cmik** [comment]
I'm closing this issue as it is too old. I think version 2.0 is fixing the issue. 
Please let me know if you are still encountering problems.
Thanks
