### ISSUE TITLE
Unable to Install on Kodi 19

### ISSUE THREAD

**Issue by austin0209** [cmik/plugin.video.tfctv#7]
Hello,

When installing tfc.tv v1.5, I get an error saying the dependency xmbc.python 2.25.0 could not be satisfied.

I have tried on both a Windows laptop and a 1st gen Firestick 4k -- both get the same error on fresh installs.

**Comment by cmik** [comment]
Hi,
The add-on is not compatible with Kodi 19 and Python 3 yet.
But you can downgrade to Kodi 18.

**Comment by blintwave** [comment]
On android tv you can not downgrade... Is there any progress on supporting Kodi 19 at the moment?

**Comment by cmik** [comment]
@blintwave,
Compatible version for Kodi 19 is still ongoing. I though it will be more easier.

**Comment by blintwave** [comment]
> @blintwave,
> Compatible version for Kodi 19 is still ongoing. I though it will be more easier.

No need to rush...if you ever need help with beta testing I can help you. Currently running Kodi 19 on Android TV ( shield tv pro ). Tho for debugging your code within Kodi I need some direction, I have no experience with it....

**Comment by cmik** [comment]
Version 2.0.0 is pushed on this Github and Cmik repo one also so more people can (auto) update their TFC.tv.
And 1.7 for Kodi 18 and below is still available on the repo : https://repo.cmik.me/tfc.tv/

**Comment by cmik** [comment]
As the add-on is now compatible with Kodi 19, I'm closing this issue.
